example/core/models.py
from task_manager.db import TaskMixin, TaskLogMixin
from sqlalchemy.ext.declarative import declarative_base
from flask_sqlalchemy import SQLAlchemy, BaseQuery, _QueryProperty

Base = declarative_base()
db = SQLAlchemy()
db.Model = Base
db.Model.query_class = BaseQuery
db.Model.query = _QueryProperty(db)


class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)


class Task(Base, TaskMixin):
    pass


class TaskLog(Base, TaskLogMixin):
    pass

example/app.py
from manage import app


if __name__ == "__main__":
    app.run(port=8050)

example/core/__init__.py
from .application import create_app

example/core/views.py
from flask_wtf.csrf import CSRFProtect
from flask import (
    Blueprint, render_template, redirect, url_for
)
from .models import Task, TaskLog
from .tasks import test_task
from .config import DevelopmentConfig
from task_manager.queue import Queue
from task_manager.db import TaskManager
from task_manager.schedule import TaskScheduler
from kafka import KafkaProducer
from random import randint
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

some_engine = create_engine(DevelopmentConfig.SQLALCHEMY_DATABASE_URI)
Session = sessionmaker(bind=some_engine)

# csrf protection
csrf = CSRFProtect()

tm = TaskManager(Task, TaskLog, Session())
producer = KafkaProducer(bootstrap_servers='127.0.0.1:9092')
queue = Queue(producer, task_manager=tm)
ts = TaskScheduler(queue)

# blueprint for news related views
news = Blueprint('news', __name__, template_folder='templates')


@news.route('/', methods=['GET'])
def overview():
    tasks = Task.query.order_by(Task.id.asc()).all()
    return render_template('overview.html', tasks=tasks)


@news.route('/new_task/', methods=['GET'])
def new_task():
    queue.enqueue("example_topic", randint(10, 40), func=test_task, use_db=True)
    return redirect(url_for('news.overview'))


@news.route('/new_simple_task/', methods=['GET'])
def new_simple_task():
    queue.enqueue("example_topic", randint(10, 40), use_db=True)
    return redirect(url_for('news.overview'))


@news.route('/postpone_task/<int:task_id>/', methods=['GET'])
def postpone_task(task_id):
    ts.postpone_task(task_id, 1)
    return redirect(url_for('news.overview'))


@news.route('/cancel_task/<int:task_id>/', methods=['GET'])
def cancel_task(task_id):
    ts.cancel_task(task_id, 1)
    return redirect(url_for('news.overview'))


@news.route('/repeat_task/<int:task_id>/', methods=['GET'])
def repeat_task(task_id):
    ts.repeat_task(task_id, 1)
    return redirect(url_for('news.overview'))

example/core/templates/overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Overview</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/font-awesome.min.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
<a class="btn btn-danger" href="/new_task/">create new task with process function</a>
<a class="btn btn-default" href="/new_simple_task/">create new task without process function</a>
<div class="row">
<div class="panel panel-default col-md-offset-1 col-md-10">
  <div class="page-header">
    Tasks
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">status</th>
          <th scope="col">created_at</th>
          <th scope="col">job_id</th>
          <th scope="col">job_topic</th>
          <th scope="col">job_key</th>
          <th scope="col">job_value</th>
          <th scope="col">job_partition</th>
          <th scope="col">result</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>

        {% for task in tasks %}
        <tr>
          <td>{{task.id}}</td>
          <td>{{task.status}}</td>
          <td>{{task.created_at}}</td>
          <td>{{task.job_id}}</td>
          <td>{{task.job_topic}}</td>
          <td>{{task.job_key}}</td>
          <td>{{task.job_value}}</td>
          <td>{{task.job_partition}}</td>
          <td>{{task.result}}</td>
          <td>
          {% if task.status.name in ('waiting', 'postponed')%}
            <a class="btn btn-info btn-xs" href="{{ url_for('news.postpone_task', task_id=task.id) }}" data-toggle="tooltip" title="" data-original-title="Postpone">Postpone</a>
            <a class="btn btn-info btn-xs" href="{{ url_for('news.cancel_task', task_id=task.id) }}" data-toggle="tooltip" title="" data-original-title="Cancel">Cancel</a>
          {% elif task.status.name != 'active' %}
            <a class="btn btn-info btn-xs" href="{{ url_for('news.repeat_task', task_id=task.id) }}" data-toggle="tooltip" title="" data-original-title="Repeat">Repeat</a>
          {% endif %}
          </td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</div>
</div>
</body>
</html>